export const UPDATE_FIELD = 'updateField'

export const POP_STEP = 'popStep'
export const PUSH_IRREGULARIDADE = 'pushIrregularidade'
export const PUSH_STEP = 'pushStep'
export const END_LOADING = 'endLoading'
export const REMOVE_IRREGULARIDADE = 'removeIrregularidade'
export const RESET_STATE = 'resetState'
export const SET_ITEMS = 'setItems'
export const SET_NOME_LOCKING = 'setNomeLocking'
export const SET_PROCESSO_ID = 'setProcessoId'
export const SET_SELECT_OPTIONS = 'setSelectOptions'
export const SET_SEARCH = 'setSearch'
export const SET_STEP_ACTION = 'setStepAction'
export const SET_STEPS = 'setSteps'
export const START_LOADING = 'startLoading'
